version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7-jammy
    container_name: bookauto-db-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: platformreserv
    volumes:
      - mongodb_data_dev:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bookauto-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookauto-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/platformreserv
      - JWT_SECRET=development-jwt-secret-please-change-in-production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads_dev:/app/uploads
    networks:
      - bookauto-network

  # Frontend React (développement)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bookauto-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_TITLE=BookAuto
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bookauto-network

networks:
  bookauto-network:
    driver: bridge

volumes:
  mongodb_data_dev:
    driver: local
  backend_uploads_dev:
    driver: local
