<<<<<<< HEAD
version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7
    container_name: rendezvous-pro-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rendezvous-pro
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    container_name: rendezvous-pro-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/rendezvous-pro
      - JWT_SECRET=development-jwt-secret-change-in-production
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  # Frontend (développement)
  frontend:
    image: node:18-alpine
    container_name: rendezvous-pro-frontend
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
=======
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/platformreserv
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
>>>>>>> d01419f8abec017db4f3a11fa6a4e19bdcc973fd
    depends_on:
      - backend

volumes:
<<<<<<< HEAD
  mongodb_data:
    driver: local
=======
  mongo-data:
>>>>>>> d01419f8abec017db4f3a11fa6a4e19bdcc973fd
