version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7
    container_name: rendezvous-pro-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rendezvous-pro
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rendezvous-pro-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/rendezvous-pro
      - JWT_SECRET=development-jwt-secret-change-in-production
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongodb_data:
    driver: local
